/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class id_dojo_Run */

#ifndef _Included_id_dojo_Run
#define _Included_id_dojo_Run
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     id_dojo_Run
 * Method:    controls
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_id_dojo_Run_controls
  (JNIEnv *, jclass);

/*
 * Class:     id_dojo_Run
 * Method:    controlUp
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_id_dojo_Run_controlUp
  (JNIEnv *, jclass);

/*
 * Class:     id_dojo_Run
 * Method:    controlDown
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_id_dojo_Run_controlDown
  (JNIEnv *, jclass);

/*
 * Class:     id_dojo_Run
 * Method:    controlRight
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_id_dojo_Run_controlRight
  (JNIEnv *, jclass);

/*
 * Class:     id_dojo_Run
 * Method:    controlLeft
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_id_dojo_Run_controlLeft
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
